Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "id_rsa_personal"
    aws.region = "us-east-1"
    aws.ami = "ami-0b715070"
    aws.tags = {
      'Name' => 'FP Demo Box'
    }

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/id_rsa_personal"
  end
end
