Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "fpollock_sa"
    aws.region = "us-east-1"
    aws.ami = "ami-e783df9c"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/id_rsa_work"
  end
end
