Vagrant.configure('2') do |config|
  config.vm.box = 'aws-dummy'
  config.vm.provider 'aws' do |aws, override|
    aws.keypair_name = 'fpollock_sa'

    aws.region = 'us-east-1'
    aws.ami = 'ami-e783df9c'
    associate_public_ip = true

    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = '~/.ssh/fpollock_sa'
  end
end
